### PR TITLE
Add full support for Jingle File Transfer and OMEMO encryption via JET

### PR DESCRIPTION
**Pull request by cmeng-git**
The original sources are derived from work done by vanitasvitae (see link below); but ported to be compatible with smack 4.4.5, and with improvements so they are ready for integration with an xmpp client implementation.
[Summer of Code 2017 – OMEMO Encrypted Jingle File Transfer in Smack](https://blog.jabberhead.tk/summer-of-code-2017/)

The pull request sources have full implementation for Jingle File Transfer, and support OMEMO encryption via JET. 
[XEP-0234: Jingle File Transfer 0.19.1 (2019-06-19)](https://xmpp.org/extensions/xep-0234.html)
[XEP-0391: Jingle Encrypted Transports 0.1.2 (2018-07-31)](https://xmpp.org/extensions/xep-0391.html)

Note: The full library has been included in aTalk v2.9.2 release.

### CODE REVIEW

**Comment by Neustradamus** [comment]
@Flowdalic: What do you think?

**Comment by Neustradamus** [comment]
@cmeng-git: Why have you closed it?

cc: @Flowdalic, @guusdk.

**Comment by cmeng-git** [comment]
I have merged the jft jet source into the main smack-atalk PR,  for easy maintenace. It is very tedious and difficult for me to keep them apart.

**Comment by Neustradamus** [comment]
PR here:
- https://github.com/igniterealtime/Smack/pull/520

**Pull request closed without merging**
