### PR TITLE
Fix documentation formatting in PayloadItem.java and ItemsExtension.java

### PR DESCRIPTION
**Pull request by linux4life798**
These commits fix some of the very broken documentation formatting in the pubsub extension directory.

I made the formatting of ItemsExtension.java similar to that of Item.java.

### CODE REVIEW

**Comment by Flowdalic** [comment]
Thanks for you contribution. Could you squash the three commits into one?

**Comment by linux4life798** [comment]
Yep, sure. Didn't know how verbose to be.

**Comment by Flowdalic** [comment]
You don't need to close a PR in order to do so. You could have simply
forcefully pushed to the source branch.

**Comment by linux4life798** [comment]
My apologies. Thanks for the tip!

**Pull request closed without merging**
