### PR TITLE
Additional Pubsub integration tests

### PR DESCRIPTION
**Pull request by guusdk**
Hi @Flowdalic - this isn't ready yet (more tests to come), hence the 'draft' status on the PR. I'm primarily interested in hearing from you if you'd accept more tests along these lines (before I start spending effort only to find it in vain). Whaddayathink?

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d429e9515b3d3c27a11b5dd52158b38da4a6fb58
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by Flowdalic** [comment]
Of course, more tests are always appreciated. 😀
FYI I am on vacation for the next three weeks, please don't expect me to merge these before I return. Feel free to fix the codestyle issues until then. You will find an Eclipse formatter and importorder settings file in Smacks 'resources' directory.

**Comment by vanitasvitae** [comment]
The PubSubIntegrationTests may reveal some of those Openfire PubSub issues that I stumbled upon some time ago (given that they still exist), so I'm looking forward to more tests :)

**Comment by guusdk** [comment]
Enjoy your holiday! There's no rush in getting these in.

I will tell you upfront that I'm not going to spend time applying code style changes.

(the rest of this comment is a rant - feel free to skip it)

After having to deal with the umpteenth project that has yet another set of code formatting tools, telling me that it is _really easy_ to do, if only I: 

- install tool Y
- apply setting X
- or jump through burning hoop Z

... yet cannot give me any valid argument that doesn't boil down to 'personal preference' (in 15 years, I've heard exactly two arguments that I believe have _some_ merit to them - both of which don't apply to any typical project) - I decided that it simply is not worth my effort - or my sanity. 

As might be clear from the length of this message: I feel strongly about this. If this means that my contributions don't get merged: so be it. I prefer that to the alternative of wasting time (and pulling hair out in the process) because I've used white space within brackets, _didn't_ use white space within brackets, ended a commit message with a full stop character, used more than 80 characters on a line, used more than 72 characters on another line, started a commit message with a capital letter, failed to configure editor Y with plugin Z so that it automatically detects settings for project X - bah. I'm getting worked up just reliving these examples, merely by typing this text. Did I mention that I feel strongly about this?

(If you made it to the end - thanks for bearing with me, and my apologies - it's been a long week).

**Comment by Flowdalic** [comment]
Thanks for the heads up on the upcoming rant.

If I had to guess, then I would say that you made a terrible experience with code-style and -format management in the past. As you self put it: It is important how easy it is to follow the rules. I believe the situation in Smack is pretty good, while not perfect: If you use Eclipse, then you just need to apply the provided settings *once* and be done.

Yes, this requires some extra steps. I am also happy to help e.g. if you use a different IDE or got stuck somewhere. Ideally there would be a gradle task which would format the codebase. We do not have such a task yet in Smack, but hopefully at some point in the future there will be one. Then I'd assume your counterargument regarding a properly formatted codebase is gone.

> If this means that my contributions don't get merged: so be it.

I may, or may not pick up the changes in such cases. Depending on how much I want them.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ef34cb7ed138ace09cfc451a12b4b1c15d798098
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by vanitasvitae** [comment]
I just tried to rebase this on the current master, but the PR is no longer compatible due to some API changes in the `ConfigureForm` and `SubscribeForm` classes.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a2a3a7e76815cbe651a68a1fbd955498cb130657
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: 97f9c50cabec4a45121cefda3ec1dea68a76525b
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: 7080982e632cdb95636edcf9867bead2fd80f19d
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by guusdk** [comment]
I've rebased and applied the API changes.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a2a3a7e76815cbe651a68a1fbd955498cb130657
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: 97f9c50cabec4a45121cefda3ec1dea68a76525b
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: 7080982e632cdb95636edcf9867bead2fd80f19d
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by vanitasvitae** [comment]
@guusdk I rebased your PR and fixed the checkstyle issues.

If you hard-reset this PRs branch to https://github.com/vanitasvitae/Smack/tree/sint-pubsub-moretests we could tackle merging this :)

**Comment by guusdk** [comment]
Thanks for this @vanitasvitae - I've rebased and force-pushed. As an aside: with your role as triager on this repository, I think you are able to do exactly that on the (my) branch that I used to create the PR. That ability can come in handy at times.

**Comment by Flowdalic** [comment]
Thanks @vanitasvitae and @guusdk

I have squashed the commits into one and created https://github.com/igniterealtime/Smack/pull/457. A first run on my end showed that some tests fail. I don't know the root cause (yet).

**Pull request closed without merging**
