### PR TITLE
Add Objects.requireNonNullOrEmpty

### PR DESCRIPTION
**Pull request by vanitasvitae**
Utility method to check, whether a collection is null or empty.

### CODE REVIEW

**Comment by akrherz** [comment]
This will come off as pedantic here, but I think this should be `requireNonNullNorEmpty`  as nor is the logical 'and is not' .

**Comment by vanitasvitae** [comment]
You're probably right. I followed the pattern in [StringUtils](https://github.com/igniterealtime/Smack/blob/master/smack-core/src/main/java/org/jivesoftware/smack/util/StringUtils.java#L447). Logically it is supposed to word `¬(null || empty)`.

**Comment by Flowdalic** [comment]
Thanks for your feedback @akrherz (which is always appreciated). I also think that you are right. We should at one point deprecate the `…OrEmpty()` variants in `Objects` and `StringUtils` in favor of `…NorEmpty()`.

**Comment by vanitasvitae** [comment]
I'll quickly do that :)

**Pull request merged**
