### PR TITLE
OMEMO

### PR DESCRIPTION
**Pull request by vanitasvitae**
Added basic OMEMO capabilities. Must be used with [smack-omemo-signal](https://github.com/vanitasvitae/smack-omemo-signal), which is GPLv3.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a71c73743bac5c7bc25a152a11381f33f4e28fc5
  * Your subject line is longer than 72 characters

 * Commit: 93b14706a2ea74996a7e62d0dfb9e2d5059f5a04
  * Your subject line is longer than 72 characters

 * Commit: a849150686660319547f45f9386be3b9351885f2
  * Your subject line is longer than 72 characters

 * Commit: dfd38a9e2bd034e59cc563705a6436eae798754d
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a71c73743bac5c7bc25a152a11381f33f4e28fc5
  * Your subject line is longer than 72 characters

 * Commit: 93b14706a2ea74996a7e62d0dfb9e2d5059f5a04
  * Your subject line is longer than 72 characters

 * Commit: a849150686660319547f45f9386be3b9351885f2
  * Your subject line is longer than 72 characters

 * Commit: dfd38a9e2bd034e59cc563705a6436eae798754d
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a71c73743bac5c7bc25a152a11381f33f4e28fc5
  * Your subject line is longer than 72 characters

 * Commit: 93b14706a2ea74996a7e62d0dfb9e2d5059f5a04
  * Your subject line is longer than 72 characters

 * Commit: a849150686660319547f45f9386be3b9351885f2
  * Your subject line is longer than 72 characters

 * Commit: dfd38a9e2bd034e59cc563705a6436eae798754d
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a71c73743bac5c7bc25a152a11381f33f4e28fc5
  * Your subject line is longer than 72 characters

 * Commit: 93b14706a2ea74996a7e62d0dfb9e2d5059f5a04
  * Your subject line is longer than 72 characters

 * Commit: a849150686660319547f45f9386be3b9351885f2
  * Your subject line is longer than 72 characters

 * Commit: dfd38a9e2bd034e59cc563705a6436eae798754d
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a71c73743bac5c7bc25a152a11381f33f4e28fc5
  * Your subject line is longer than 72 characters

 * Commit: 93b14706a2ea74996a7e62d0dfb9e2d5059f5a04
  * Your subject line is longer than 72 characters

 * Commit: a849150686660319547f45f9386be3b9351885f2
  * Your subject line is longer than 72 characters

 * Commit: dfd38a9e2bd034e59cc563705a6436eae798754d
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by Flowdalic** [comment]
Shouldn't this be based on the 4.2 branch? Or do you want this to be included in 4.3? If not, I would recommend creating a new PR (since github doesn't allow changing the destination branch) *when* your have your changes into a state where "gradle check" runs without errors.

**Pull request closed without merging**
