### PR TITLE
Handle redundant API: getField(..)/read(..) inside FilledForm

### PR DESCRIPTION
**Pull request by adiaholic**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0f4b582ae13c6808eb618100c7eeb00943ff54ed
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by vanitasvitae** [comment]
I'm not sure if this is desired.
The `read()` method comes from the `FormReader` class and is probably not really part of the API that `FilledForm` tries to provide. Removing the `getField()` method would make the API seem incomplete as there is `hasField()`, `getFieldOrThrow()`, but no more `getField()`. Having to use `read()` would break the "field-pattern" of the API.

**Comment by Flowdalic** [comment]
I am torn on this too, but I was about to merge this. On the other hand, it was me who introduced getField() because I assumed that a method with that functionality was missing.

Another option would be to rename `read()` in `FormFieldReader` to `getField()`, but this method was named `read` because of the corresponding `write` in `FormFieldWriter`…. wait I just noticed something.

**Comment by Flowdalic** [comment]
Closed with https://github.com/igniterealtime/Smack/commit/c5212c20b610e64eab125990c9fa67ee65e79864

**Pull request closed without merging**
