### PR TITLE
Bouncy Castle 1.65 instead of 1.64

### PR DESCRIPTION
**Pull request by Neustradamus**
Bouncy Castle 1.65 instead of 1.64: https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 23728b57deea50fc8a30236865a7b03a0b7936a5
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by Neustradamus** [comment]
How change it?

**Comment by adiaholic** [comment]
You might want to use `--amend flag` with git.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 23728b57deea50fc8a30236865a7b03a0b7936a5
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Pull request closed without merging**
