### PR TITLE
Better error messages when using a Proxy to connect to the XMPP server.

### PR DESCRIPTION
**Pull request by Basskrapfen**
When proxy connection fails, show  more error details. Before it was only a general proxy error.

### CODE REVIEW

**Comment by Basskrapfen** [comment]
Also do not use "Host: CONNECT server:port" but "Host: server:port" to connect to the proxy. My squid proxy seems to tolerate it, but this is not according to the standard.

**Comment by Basskrapfen** [comment]
> Thanks for your contribution. But please fix the CI errors.

Done.

**Comment by Flowdalic** [comment]
> Done.

Could you squash it into the related commit?

**Comment by Basskrapfen** [comment]
> > Done.
> 
> Could you squash it into the related commit?

Hm, not sure if I can still do that in this pull-request. I would need to create a different branch to squash the commits and re-create the pull-request. But I'm not really familiar with GitHub I have to admit.
In the description of GitHub it says when merging the pull-request there is an option to squash it. So maybe you can just squash with one click. - "When you select the Squash and merge option on a pull request on GitHub, the pull request's commits are squashed into a single commit." - https://help.github.com/en/articles/about-pull-request-merges

**Comment by Flowdalic** [comment]
> Hm, not sure if I can still do that in this pull-request.

Yep, simply force push to the source branch of this PR after you have squashed the commit.

**Comment by Basskrapfen** [comment]
> > Hm, not sure if I can still do that in this pull-request.
> 
> Yep, simply force push to the source branch of this PR after you have squashed the commit.

Thanks, you were right and learned something new :)

**Comment by Flowdalic** [comment]
Applied as

https://github.com/Flowdalic/Smack/commit/3450ffad2b8ea4ae1015c81146f6efe23515852a
https://github.com/Flowdalic/Smack/commit/8e88cd2e31a744bf9c5d8e599d38796b927c0413
https://github.com/Flowdalic/Smack/commit/007a04c4fe599bbea04fdd4bc6cf03e45ae8db36

**Comment by Basskrapfen** [comment]
> Applied as
> 
> [Flowdalic@3450ffa](https://github.com/Flowdalic/Smack/commit/3450ffad2b8ea4ae1015c81146f6efe23515852a)
> [Flowdalic@8e88cd2](https://github.com/Flowdalic/Smack/commit/8e88cd2e31a744bf9c5d8e599d38796b927c0413)
> [Flowdalic@007a04c](https://github.com/Flowdalic/Smack/commit/007a04c4fe599bbea04fdd4bc6cf03e45ae8db36)

Thanks a lot!

**Pull request closed without merging**
