### PR TITLE
Rework support for XEP-0384: OMEMO Encryption

### PR DESCRIPTION
**Pull request by vanitasvitae**
This PR ditches trust management from the OMEMO store. The store now only stores keys and the users ratchet. By doing so, the OmemoManager can be created while the client is offline. Once it comes online, it retrieves the users BareJid for usage with the OmemoStore.

*THIS IS STILL WORK IN PROGRESS*
Feeback appreciated.

Changes:
* Rework integration tests
* New structure of base integration test classes
* bump dependency on signal-protocol-java from 2.4.0 to 2.6.2
* Introduced CachingOmemoStore implementations
* Use CachingOmemoStore classes in integration tests
* Removed OmemoSession classes (replaced with more logical OmemoRatchet classes)
* Consequently also removed load/storeOmemoSession methods from OmemoStore
* Removed some clutter from KeyUtil classes
* Moved trust decision related code from OmemoStore to TrustCallback
* Require authenticated connection for many functions
* Add async initialization function in OmemoStore
* Refactor omemo test package (`/java/org/jivesoftware/smack/omemo` -> `/java/org/jivesoftware/smackx`)
* Remove OmemoStore method `isFreshInstallation()` as well as defaultDeviceId related stuff
* FileBasedOmemoStore: Add cleaner methods to store/load base data types (Using tryWithResource, only for future releases, once Android API gets bumped)
* Attempt to make OmemoManager thread safe
* new logic for `getInstanceFor()` deviceId determination
* OmemoManagers encrypt methods now don't throw exceptions when encryption for some devices fails. Instead message gets encrypted when possible and more information about failures gets returned alongside the message itself
* Added OmemoMessage class for that purpose
* Reworked entire OmemoService class
* Use safer logic for creating trust-ignoring messages (like ratchet-update messages)
* Restructure elements/provider in order to prepare for OMEMO namespace bumps
* Remove `OmemoManager.regenerate()` methods in favor of `getInstanceFor(connection, randomDeviceId)`
* Removed some unnecessary configuration options
* Prepare for support of more AES message key types
* Simplify session creation
* Where possible, avoid side effects in methods
* Add UntrustedOmemoIdentityException
* Add TrustState enum
* More improved tests

TODO:
* [x] Reimplement message decryption
* [x] Reimplement stanza listening
* [x] Reimplement PEP listeners
* [x] Reimplement support for MAM queries
* [x] Reimplement some more convenience methods
* [ ] More testing
* [ ] Implement client side support for publish options
-------------------------------------------------------------------
* [x] Document changes
* [ ] Create migration guide
* [x] Rant about OMEMOs quirks

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 80db75265465657295d0cd2a0432eaf7909e2d76
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4ed3adf5603d5f13f7e2fa85a9e2bd19e91a45a7
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by bansiRohit** [comment]
Hi ,
I want to implement xmpp chat , so please guide me

**Comment by vanitasvitae** [comment]
@bansiRohit this is not a support forum. Please visit https://discourse.igniterealtime.org/ instead. Also please think about a better question to ask ;)

**Comment by cmeng-git** [comment]
Whenever user acquired new device, regenerate omemo identity or reinstall the app, a new omemoDevice is created and published to the server. Overtime, this deviceList gets larger and becomes unmanageable. In aTalk when user starts new to setup a omemo session with this buddy for the first time, he/she is presented with a long list of omemo identities to trust, including the unused identities. This really confuse the user.
Does your new release take care or would consider to implement the removal of unused omemoDevice that were previously published on the server.

**Comment by vanitasvitae** [comment]
@cmeng-git devices, which do not send a message for an extended period of time will get ignired after a while and even deleted from the list when no message is received for some time. Also there is the method putgeDeviceList, which deletes all but the device of the user from the list.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b70e80b1ad9a581ac4daeec874949e90f2db2c0a
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by vanitasvitae** [comment]
Rebased on and now targeting master branch

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a07a0ac861ecc3ebacccb19fcd3856d43190fe76
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 3851b952b0b35759b7f2de6cb22d772f53a043b8
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1f731f6318785a84b9741280d586a61dc37ecb2e
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
