### PR TITLE
IQProvider correction

### PR DESCRIPTION
**Pull request by Neustradamus**
- Remove old IQProvider.java
- Rename IqProvider.java file to IQProvider.java
- Replace IqProvider -> IQProvider

### CODE REVIEW

**Comment by Flowdalic** [comment]
`IqProvider` is determined to be the future abstract superclass for IQ providers, so renaming it to `IQProvider` is not an option. What somebody needs to do is to switch call usages of `IQProvider` to use `IqProvider` instead.

**Comment by Neustradamus** [comment]
@Flowdalic: There is a problem not new:
- https://discourse.igniterealtime.org/t/problem-when-we-fork-the-github/87670

If you want I can rename the original IqProvider.java to  IqProvider2.java.

**Comment by ibauersachs** [comment]
> What somebody needs to do is to switch call usages of `IQProvider` to use `IqProvider` instead.

@Flowdalic do you have a timeline for the 4.5 release? I might give this a try, but I'd need some time.

**Comment by Flowdalic** [comment]
This PR is now obsolete due to #523.

**Pull request closed without merging**
