### PR TITLE
Add OmemoClient to smack-repl

### PR DESCRIPTION
**Pull request by vanitasvitae**
;)

### CODE REVIEW

**Comment by Flowdalic** [comment]
Could you remove 9f86eda from this PR, since it is already parts of PR #337, if possible?

**Comment by vanitasvitae** [comment]
> Could you remove 9f86eda from this PR, since it is already parts of PR #337, if possible?

What would be the easiest way to do this? I mean, I could just rebase this on master once #337 is merged.

**Comment by Flowdalic** [comment]
> What would be the easiest way to do this? I mean, I could just rebase this on master once #337 is merged.

Git's interactive rebase tool allows you to delete commits by deleting commit lines in question. See also: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

Then force push the branch.

**Comment by Flowdalic** [comment]
Applied with modifications as https://github.com/igniterealtime/Smack/commit/3a0356488da91c3e6f42ecae90e16dbe42ef9596

**Pull request closed without merging**
