### PR TITLE
Update Nick.java

### PR DESCRIPTION
**Pull request by UltimateZero**
Use empty string in case of an empty element tag.

### CODE REVIEW

**Comment by Flowdalic** [comment]
Thanks. Could you go with the slightly more optimized approach of

```java
String name;
if (parser.isEmptyElement()) {
  name = "";
} else {
  name = parser.getText();
}
```
then squash your commits into a single commit and update this PR by performing a force push.

**Comment by Flowdalic** [comment]
Perfect! Now please squash.

**Comment by UltimateZero** [comment]
@Flowdalic Hi, I am not sure if you got a notification or not, but I have squashed the commits. Anything else missing?

**Comment by Flowdalic** [comment]
I was just about to cherry-pick this (In fact I already did) when I realized that the real fix is

```diff
-            parser.next();
-			final String name = parser.getText();
+            final String name = parser.nextText();
```

Feel free to update the PR according to this. If not, then please let me know so that I can commit it myself.

**Comment by UltimateZero** [comment]
Ah I didn't know that existed, I was just following the old code.
Ok done and squashed into one commit.

**Comment by Flowdalic** [comment]
Closed via https://github.com/igniterealtime/Smack/commit/df0f805febc6d5b293f88abbd5d355a0d42fc445

**Pull request closed without merging**
