### PR TITLE
Smack 4.0.7-SNAPSHOT

### PR DESCRIPTION
**Pull request by nikanj**

### CODE REVIEW

**Comment by nikanj** [comment]
Integrate exi with smack

**Comment by Flowdalic** [comment]
I'm sorry, but: whut?

I guess there went something wrong when you prepared the commit/PR.

**Comment by Flowdalic** [comment]
Closing till I get a response what's this is about.

**Comment by nikanj** [comment]
Hi,

  I have integrated exi with the latest version of smack and wanted to
upstream it. You could then have a look at the code and decide if it is
worth going ahead.

With Regards,
Nikanj.

**Comment by Flowdalic** [comment]
> I have integrated exi with the latest version of smack and wanted to
> upstream it. You could then have a look at the code and decide if it is
> worth going ahead.

Would be happy to do so, just show me the code. :)

**Pull request closed without merging**
