### PR TITLE
Add DOAP file for Smack

### PR DESCRIPTION
**Pull request by guusdk**
The structured description of the Smack project can be used by software to generate listings. The XMPP.org website uses it.

fixes SMACK-879

### CODE REVIEW

**Comment by guusdk** [comment]
This can be enhanced by adding the XEPs that Smack supports. That's one bridge to far for me now.

**Comment by guusdk** [comment]
After merging, the file in https://github.com/xsf/xmpp.org/blob/master/data/software.json should be updated to reference this file in our repository, so that updates are automatically shown on the xmpp.org website.

**Comment by Flowdalic** [comment]
Thanks, much appreciated! :)

**Comment by guusdk** [comment]
https://github.com/xsf/xmpp.org/pull/1447

**Pull request merged**
