### PR TITLE
Fixing typo to make example compile

### PR DESCRIPTION
**Pull request by hintzed**
Only a trivial typo, but since I just stumbled across it, I thought I
might as well fix it. Hope you don't mind the overhead for doing a pull
request.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e2d4e7b9953caeb37b51ee9c35d5c9d29082f4e8
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e2d4e7b9953caeb37b51ee9c35d5c9d29082f4e8
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by hintzed** [comment]
I (think?) I fixed the GitCop warning - sorry.

**Comment by Flowdalic** [comment]
Thanks, please squash the commits into one.

**Comment by hintzed** [comment]
Squashed

**Pull request merged**
