### PR TITLE
Fix missing body namespace in BOSH messages

### PR DESCRIPTION
**Pull request by mhariri**
The body's "jabber:client" namespace was missing
in BOSH messages.

### CODE REVIEW

**Comment by vanitasvitae** [comment]
Hi!
Thank you for your contribution! Unfortunately there are some checkstyle issues with it. More specifically, now there are unused imports in `XMPPBOSHConnection`. Please fix those issues.

You can check, whether all issues are fixed by running `gradle check` while in the Smack folder.

**Comment by mhariri** [comment]
Fixed. Let's see if it passes the build now.

**Comment by vanitasvitae** [comment]
It does :)

**Comment by Flowdalic** [comment]
Could you re-issue this PR against the 4.3 branch?

**Comment by mhariri** [comment]
Sure, will open a new PR.

**Pull request closed without merging**
