### PR TITLE
4.4

### PR DESCRIPTION
**Pull request by cmeng-git**
Thank you for your contribution!

Before creating a Pull Request, please make sure to
* read https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors
* run `gradle check` successfully in order to make sure that your code does not break any JUnit tests and is conform to the projects code style.
* (if applicable) mention any Jira issue codes (eg. `SMACK-XXX`) in the *body* of your commit message (not the header), so that Jira automatically links the PR to the issue.
* squash your commits if possible/sensible.

### CODE REVIEW

**Comment by cmeng-git** [comment]
Pull request: Do not send 'close' element on an already closed InBandByteStream session

**Comment by Flowdalic** [comment]
As always, thanks for your contribution. The basic approach looks right from a quick look at it. But could you please avoid mixing whitespace only changes with code-semantic changes in the same commit (ideally the whitespace changes would be an extra PR)? Furthermore, please remove the merge commit from the PR.

**Comment by cmeng-git** [comment]
Due to my ignore to Github, seems like I have meshed up my smack forked branch 4.4.

Trying to resolve the following, attempted but create more problems. Need your help on this, or kindly direct me to a site that provides instruction how to do this.

> please remove the merge commit from the PR

**Comment by Flowdalic** [comment]
I find the Pro Git book a good read: https://git-scm.com/book/en/v2.

**Pull request closed without merging**
