### PR TITLE
Fixes a memory leak, leaking MultiUserChat instances.

### PR DESCRIPTION
**Pull request by damencho**

### CODE REVIEW

**Comment by damencho** [comment]
@Flowdalic is there a planned smack 4.2 update?

**Comment by Flowdalic** [comment]
Thanks for you contribution. I've created SMACK-782 to track this. Could you add the issue key to the commit message. Simply "Fixes SMACK-782" in the message body would be sufficient. While add it, please change the commit subject to what you actually do, e.g. "Fix memory leak by removing subject listener in MutliUserChat.removeConnectionCallback()".

> @Flowdalic is there a planned smack 4.2 update?

I usually recommend consumers to first verify that the issue is really fixed by using the nightly unique snapshot artifacts from ignitrealtime.org/repo. But I'm also very agile and flexible about creating and publishing a new release. Thanks to Maven Central it's just a matter of a few bash commands ;) Also I was planning to release 4.2.2 soon™. So if the unique snapshots artifacts don't work for you, when do you want a new release?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e56d089f384d0870285b2f0b54b1cf614db82af8
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 003dd06a4c95f5050d590a76a1db2ab4d16718a6
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/igniterealtime/Smack/wiki/Guidelines-for-Smack-Developers-and-Contributors

---
This message was auto-generated by https://gitcop.com

**Comment by Flowdalic** [comment]
I've cherry picked you first commit as https://github.com/Flowdalic/Smack/commit/44e4607259fddf0c3d6b75ea78cb01ef4583e3ed and decided to go with a slightly different approach regarding your second commit: https://github.com/Flowdalic/Smack/commit/5ef6853db6873115d53d9bb65780b6f5a8d549f9

Those are currently only available in my personal github repo. Will move them to the offical once travis passes.

> When are the snapshots generated? 

Every night if there are new commits.

**Comment by Flowdalic** [comment]
Cherry picked as https://github.com/igniterealtime/Smack/commit/44e4607259fddf0c3d6b75ea78cb01ef4583e3ed

**Pull request closed without merging**
