### PR TITLE
Make abstract package protected methods in PEPItem public

### PR DESCRIPTION
**Pull request by rvaibhav**
fixes SMACK-372

### CODE REVIEW

**Comment by Flowdalic** [comment]
Thanks for your contribution.

Could you shorten the subject of the commit message so that it follows the 50/72 rule. E.g. "Make abstarct PEPItem methods public". Also please mention the issue key "SMACK-372" somehwere in the commit messages body.

**Comment by rvaibhav** [comment]
@Flowdalic to shorten the git message shall I open a new pull request and close this one?

**Comment by Flowdalic** [comment]
No you can update existing PRs by just issuing a *forced* push to the source branch.

**Comment by rvaibhav** [comment]
@Flowdalic ammended the commit message.
Can you please review again.

Thanks

**Comment by Flowdalic** [comment]
There is a missing space between "abstract" and "package". Also please don't put the issue key in the subject. Simply add

Fixes SMACK-372

in the body.

**Comment by rvaibhav** [comment]
@Flowdalic Made changes as per review comments. Please review again.

**Comment by Flowdalic** [comment]
The issue key is still part of the subject. Cherry picked with minor modifications as https://github.com/igniterealtime/Smack/commit/3bbffeae285d2467d8829d3e9f63fd7d7de11dd4

**Comment by rvaibhav** [comment]
Issue key is "Make abstract package protected methods in PEPItem public"
or "SMACK-372"?

Wanted to confirm so that I do not goof up in future commits.

Thanks
Vaibhav

**Comment by Flowdalic** [comment]
SMACK-372 is the (JIRA) issue key

**Comment by rvaibhav** [comment]
Thanks!

**Pull request closed without merging**
